# Generated by Django 4.2.27 on 2026-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='img_path',
        ),
        migrations.AddField(
            model_name='payment',
            name='slip_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
