# Generated by Django 4.2.27 on 2026-07-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_payment_img_path_payment_slip_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ຍັງບໍ່ຊຳລະ'), ('PARTIAL', 'ຊຳລະບາງສ່ວນ'), ('PAID', 'ຊຳລະຄົບ')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ລໍຖ້າ'), ('RESERVED', 'ຈອງ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_with',
            field=models.CharField(choices=[('CASH', 'ເງິນສົດ'), ('TRANSFER', 'ໂອນ'), ('QR', 'QR')], default='TRANSFER', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'ຈອງ'), ('PAID', 'ຊຳລະຄົບ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='RESERVED', max_length=30),
        ),
    ]
