# Generated by Django 4.2.27 on 2026-07-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_bill_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'ບິນ (Bill)', 'verbose_name_plural': 'ບິນ (Bills)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'ອໍເດີ (Order)', 'verbose_name_plural': 'ອໍເດີ (Orders)'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ລາຍການອໍເດີ (Order Item)', 'verbose_name_plural': 'ລາຍການອໍເດີ (Order Items)'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'ການຊຳລະເງິນ (Payment)', 'verbose_name_plural': 'ການຊຳລະເງິນ (Payments)'},
        ),
        migrations.AlterModelOptions(
            name='reserved',
            options={'verbose_name': 'ສິນຄ້າຈອງ (Reserved)', 'verbose_name_plural': 'ສິນຄ້າຈອງ (Reserved)'},
        ),
    ]
