# Generated by Django 4.2.27 on 2026-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_bill_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserved',
            name='stock_ready',
            field=models.BooleanField(default=False, help_text='ອັດຕະໂນມັດ True ເມື່ອສິນຄ້າໃໝ່ເຂົ້າ ແລະ ຈັດສັນໃຫ້ການຈອງນີ້ແລ້ວ', verbose_name='ສິນຄ້າພ້ອມ (Stock ready)'),
        ),
    ]
