# Generated by Django 4.2.27 on 2026-07-14 14:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_name_alter_product_category_and_more'),
        ('store', '0003_alter_customer_options_alter_employee_options_and_more'),
        ('sales', '0005_reserved_stock_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'ອໍເດີ (Orders)', 'verbose_name_plural': 'ອໍເດີ (Orders)'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ລາຍລະອຽດ (Order_detail)', 'verbose_name_plural': 'ລາຍລະອຽດ (Order_detail)'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Balance_due'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bill_date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='sales.order', verbose_name='Order_ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Paid_amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ຍັງບໍ່ຊຳລະ'), ('PARTIAL', 'ຊຳລະບາງສ່ວນ'), ('PAID', 'ຊຳລະຄົບ')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total_amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customer', verbose_name='Cus_ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='nullable ສຳລັບ web order (ບົດ: NOT NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='store.employee', verbose_name='Emp_ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order_date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ລໍຖ້າ'), ('RESERVED', 'ຈອງ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Order_ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Pro_ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.bill', verbose_name='Bill_ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='store.employee', verbose_name='Emp_ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Pay_amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Pay_date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_with',
            field=models.CharField(choices=[('CASH', 'ເງິນສົດ'), ('TRANSFER', 'ໂອນ'), ('QR', 'QR')], default='TRANSFER', max_length=50, verbose_name='Pay_with'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slip_url',
            field=models.CharField(blank=True, help_text='ບົດ: Img_path — URL ຮູບ slip ຈາກ Supabase', max_length=500, null=True, verbose_name='Img_path (Slip URL)'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Deposit_amount'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='expire_at',
            field=models.DateTimeField(verbose_name='Expire_at'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sales.order', verbose_name='Order_ID'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Pro_ID'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Remain_amount'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='res_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Res_date'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'ຈອງ'), ('PAID', 'ຊຳລະຄົບ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='RESERVED', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='stock_ready',
            field=models.BooleanField(default=False, help_text='ເພີ່ມຕອນ implement — ສິນຄ້າຈັດໃຫ້ຈອງແລ້ວ (ບົດບໍ່ມີ)', verbose_name='Stock_ready (impl.)'),
        ),
    ]
