# Generated by Django 4.2.27 on 2026-07-23 13:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_options_alter_employee_options_and_more'),
        ('catalog', '0006_alter_category_options_alter_product_options_and_more'),
        ('sales', '0006_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'ບິນ', 'verbose_name_plural': 'ບິນ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'ອໍເດີ', 'verbose_name_plural': 'ອໍເດີ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'ລາຍການໃນອໍເດີ', 'verbose_name_plural': 'ລາຍການໃນອໍເດີ'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'ການຊຳລະເງິນ', 'verbose_name_plural': 'ການຊຳລະເງິນ'},
        ),
        migrations.AlterModelOptions(
            name='reserved',
            options={'verbose_name': 'ການຈອງສິນຄ້າ', 'verbose_name_plural': 'ການຈອງສິນຄ້າ'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຄ້າງຊຳລະ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີບິນ'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='sales.order', verbose_name='ອໍເດີ'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຈ່າຍແລ້ວ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ຍັງບໍ່ຊຳລະ'), ('PARTIAL', 'ຊຳລະບາງສ່ວນ'), ('PAID', 'ຊຳລະຄົບ')], default='PENDING', max_length=30, verbose_name='ສະຖານະບິນ'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຍອດທັງໝົດ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='ອໍເດີຈາກເວັບມັກມີລູກຄ້າ · POS ອາດບໍ່ມີ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customer', verbose_name='ລູກຄ້າ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='ຜູ້ຂາຍໜ້າຮ້ານ (POS). ອໍເດີເວັບອາດປ່ອຍວ່າງໄດ້', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='store.employee', verbose_name='ພະນັກງານ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີສັ່ງ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ລໍຖ້າ'), ('RESERVED', 'ຈອງ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='PENDING', help_text='ລໍຖ້າ = ຍັງບໍ່ຈ່າຍ · ສຳເລັດ = ຈ່າຍ/ຮັບເຄື່ອງແລ້ວ', max_length=30, verbose_name='ສະຖານະ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='ອໍເດີ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ລາຄາ/ຫນ່ວຍ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='ສິນຄ້າ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='ຈຳນວນ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ລວມແຖວ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.bill', verbose_name='ບິນ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='store.employee', verbose_name='ພະນັກງານຮັບເງິນ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຈຳນວນເງິນ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີຈ່າຍ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_with',
            field=models.CharField(choices=[('CASH', 'ເງິນສົດ'), ('TRANSFER', 'ໂອນ'), ('QR', 'QR')], default='TRANSFER', max_length=50, verbose_name='ວິທີຈ່າຍ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slip_url',
            field=models.CharField(blank=True, help_text='ລິ້ງຮູບໂອນເງິນທີ່ລູກຄ້າອັບໂຫຼດ — ພະນັກງານກວດໃນໜ້າ Staff', max_length=500, null=True, verbose_name='ລິ້ງຮູບສະລິບ'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ເງິນທີ່ລູກຄ້າຈ່າຍກ່ອນ (ປົກກະຕິ 50%)', max_digits=12, verbose_name='ມັດຈຳ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='expire_at',
            field=models.DateTimeField(help_text='ຫຼັງວັນນີ້ການຈອງອາດຖືກຍົກເລີກ', verbose_name='ໝົດອາຍຸຈອງ'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sales.order', verbose_name='ອໍເດີ'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='ສິນຄ້າ'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='ຈຳນວນ'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ເງິນທີ່ຕ້ອງຈ່າຍເພີ່ມເມື່ອຮັບສິນຄ້າ', max_digits=12, verbose_name='ຄ້າງຈ່າຍ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='res_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີຈອງ'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'ຈອງ'), ('PAID', 'ຊຳລະຄົບ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='RESERVED', max_length=30, verbose_name='ສະຖານະຈອງ'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='stock_ready',
            field=models.BooleanField(default=False, help_text='ຕິກເມື່ອສິນຄ້າມາຮອດ/ຈັດໃຫ້ການຈອງນີ້ແລ້ວ — ລູກຄ້າສາມາດມາຮັບໄດ້', verbose_name='ສິນຄ້າພ້ອມແລ້ວ'),
        ),
    ]
