# Generated by Django 4.2.27 on 2026-08-25 06:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_options_alter_employee_options_and_more'),
        ('sales', '0007_alter_bill_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customer', verbose_name='ລູກຄ້າ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='store.employee', verbose_name='ພະນັກງານ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ລໍຖ້າ'), ('RESERVED', 'ຈອງ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='PENDING', max_length=30, verbose_name='ສະຖານະ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ລາຄາ/ໜ່ວຍ (ກີບ)'),
        ),
    ]
