services:
  - type: web
    name: matcha_shopbeta
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn config.wsgi --workers 1 --bind 0.0.0.0:$PORT --timeout 120
    healthCheckPath: /healthz/
