# Generated by Django 4.2.27 on 2026-07-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'ລູກຄ້າ (Customer)', 'verbose_name_plural': 'ລູກຄ້າ (Customers)'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'ພະນັກງານ (Employee)', 'verbose_name_plural': 'ພະນັກງານ (Employees)'},
        ),
    ]
