# Generated by Django 4.2.27 on 2026-07-14 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_customer_options_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'ລູກຄ້າ (Customer)', 'verbose_name_plural': 'ລູກຄ້າ (Customer)'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'ພະນັກງານ (Employee)', 'verbose_name_plural': 'ພະນັກງານ (Employee)'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_last',
            field=models.CharField(max_length=100, verbose_name='Cus_Last'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_name',
            field=models.CharField(max_length=100, verbose_name='Cus_Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_tel',
            field=models.CharField(max_length=20, verbose_name='Cus_Tel'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='ບົດ: Email, Password — Django ເກັບໃນ auth_user (hash)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Email / Password (auth_user)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_address',
            field=models.TextField(verbose_name='Emp_Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(max_length=10, verbose_name='Emp_Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_last',
            field=models.CharField(max_length=100, verbose_name='Emp_Last'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=100, verbose_name='Emp_Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_tel',
            field=models.CharField(max_length=20, verbose_name='Emp_Tel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(help_text='ບົດ: Email, Password — Django ເກັບໃນ auth_user (hash)', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Email / Password (auth_user)'),
        ),
    ]
