# Generated by Django 4.2.27 on 2026-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_paymentconfirmation_slip_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weborder',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('WAITING_PAYMENT', 'WAITING_PAYMENT'), ('PAYMENT_REVIEW', 'PAYMENT_REVIEW'), ('PAID', 'PAID'), ('SHIPPING', 'SHIPPING'), ('DONE', 'DONE'), ('CANCEL', 'CANCEL')], default='NEW', max_length=30),
        ),
    ]
