# Generated by Django 4.2.27 on 2026-07-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_customer_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'ລູກຄ້າ', 'verbose_name_plural': 'ລູກຄ້າ'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'ພະນັກງານ', 'verbose_name_plural': 'ພະນັກງານ'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(help_text='ໃຊ້ສຳລັບສົ່ງສິນຄ້າ', verbose_name='ທີ່ຢູ່ / ທີ່ຈັດສົ່ງ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_last',
            field=models.CharField(max_length=100, verbose_name='ນາມສະກຸນ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_name',
            field=models.CharField(max_length=100, verbose_name='ຊື່'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_tel',
            field=models.CharField(help_text='ເບີຕິດຕໍ່ລູກຄ້າ (ສຳຄັນ)', max_length=20, verbose_name='ເບີໂທ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='ເພດ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='ຖ້າລູກຄ້າລົງທະບຽນເວັບ — ເຊື່ອມກັບ User. ລູກຄ້າ POS ອາດປ່ອຍວ່າງໄດ້', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='ບັນຊີເຂົ້າລະບົບ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_address',
            field=models.TextField(verbose_name='ທີ່ຢູ່'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(help_text='ຕົວຢ່າງ: ຊາຍ / ຍິງ', max_length=10, verbose_name='ເພດ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_last',
            field=models.CharField(max_length=100, verbose_name='ນາມສະກຸນ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=100, verbose_name='ຊື່'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_tel',
            field=models.CharField(help_text='ເບີຕິດຕໍ່ພະນັກງານ', max_length=20, verbose_name='ເບີໂທ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(help_text='ເຊື່ອມກັບ User (ອີເມວ/ຊື່ຜູ້ໃຊ້ + ລະຫັດ) — ສຳລັບ login ພະນັກງານ', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='ບັນຊີເຂົ້າລະບົບ'),
        ),
    ]
