# Generated by Django 4.2.27 on 2026-07-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ລໍຖ້າ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='PENDING', max_length=30),
        ),
    ]
