# Generated by Django 4.2.27 on 2026-07-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_importdetail_created_at_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importdetail',
            options={'verbose_name': 'ລາຍລະອຽດນຳເຂົ້າ (Import Detail)', 'verbose_name_plural': 'ລາຍລະອຽດນຳເຂົ້າ (Import Details)'},
        ),
        migrations.AlterModelOptions(
            name='imports',
            options={'verbose_name': 'ນຳເຂົ້າ (Import)', 'verbose_name_plural': 'ນຳເຂົ້າ (Imports)'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'ສິນຄ້າໃນສາງ (Stock)', 'verbose_name_plural': 'ສິນຄ້າໃນສາງ (Stock)'},
        ),
        migrations.AlterModelOptions(
            name='podetail',
            options={'verbose_name': 'ລາຍລະອຽດໃບສັ່ງຊື້ (PO Detail)', 'verbose_name_plural': 'ລາຍລະອຽດໃບສັ່ງຊື້ (PO Details)'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'ໃບສັ່ງຊື້ (Purchase Order)', 'verbose_name_plural': 'ໃບສັ່ງຊື້ (Purchase Orders)'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'ຜູ້ສະໜອງ (Supplier)', 'verbose_name_plural': 'ຜູ້ສະໜອງ (Suppliers)'},
        ),
    ]
