# Generated by Django 4.2.27 on 2026-07-14 14:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_name_alter_product_category_and_more'),
        ('store', '0003_alter_customer_options_alter_employee_options_and_more'),
        ('inventory', '0003_alter_importdetail_options_alter_imports_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importdetail',
            options={'verbose_name': 'ລາຍລະອຽດນຳເຂົ້າ (Import_detail)', 'verbose_name_plural': 'ລາຍລະອຽດນຳເຂົ້າ (Import_detail)'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'ສິນຄ້າໃນສາງ (Inventory)', 'verbose_name_plural': 'ສິນຄ້າໃນສາງ (Inventory)'},
        ),
        migrations.AlterModelOptions(
            name='podetail',
            options={'verbose_name': 'ລາຍລະອຽດ PO (PO_detail)', 'verbose_name_plural': 'ລາຍລະອຽດ PO (PO_detail)'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'ໃບສັ່ງຊື້ (Purchase_order)', 'verbose_name_plural': 'ໃບສັ່ງຊື້ (Purchase_order)'},
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cost_price'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='imports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.imports', verbose_name='Imp_ID'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Pro_ID'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.employee', verbose_name='Emp_ID'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='imp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Imp_date'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder', verbose_name='PO_ID'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Sup_ID'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total_amount'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry_date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product', verbose_name='Pro_ID'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cost_price'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Pro_ID'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.purchaseorder', verbose_name='PO_ID'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.employee', verbose_name='Emp_ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='PO_date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ລໍຖ້າ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Sup_ID'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total_amount'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_address',
            field=models.TextField(verbose_name='Sup_Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_name',
            field=models.CharField(max_length=100, verbose_name='Sup_Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_tel',
            field=models.CharField(max_length=20, verbose_name='Sup_Tel'),
        ),
    ]
