# Generated by Django 4.2.27 on 2026-07-23 13:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_options_alter_employee_options_and_more'),
        ('catalog', '0006_alter_category_options_alter_product_options_and_more'),
        ('inventory', '0004_alter_importdetail_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importdetail',
            options={'verbose_name': 'ລາຍການນຳເຂົ້າ', 'verbose_name_plural': 'ລາຍການນຳເຂົ້າ'},
        ),
        migrations.AlterModelOptions(
            name='imports',
            options={'verbose_name': 'ນຳເຂົ້າສິນຄ້າ', 'verbose_name_plural': 'ນຳເຂົ້າສິນຄ້າ'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'ສະຕັອກໃນສາງ', 'verbose_name_plural': 'ສະຕັອກໃນສາງ'},
        ),
        migrations.AlterModelOptions(
            name='podetail',
            options={'verbose_name': 'ລາຍການໃບສັ່ງຊື້', 'verbose_name_plural': 'ລາຍການໃບສັ່ງຊື້'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'ໃບສັ່ງຊື້', 'verbose_name_plural': 'ໃບສັ່ງຊື້'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'ຜູ້ສະໜອງ', 'verbose_name_plural': 'ຜູ້ສະໜອງ'},
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຕົ້ນທຶນ/ຫນ່ວຍ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ວັນທີບັນທຶກ'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='imports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.imports', verbose_name='ໃບນຳເຂົ້າ'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='ສິນຄ້າ'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='ເມື່ອບັນທຶກ — ລະບົບເພີ່ມສະຕັອກອັດຕະໂນມັດ', verbose_name='ຈຳນວນ'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ລວມແຖວ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.employee', verbose_name='ພະນັກງານຮັບເຂົ້າ'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='imp_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີນຳເຂົ້າ'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder', verbose_name='ໃບສັ່ງຊື້'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='ຜູ້ສະໜອງ'),
        ),
        migrations.AlterField(
            model_name='imports',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຍອດລວມ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີເພີ່ມ'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='ປ່ອຍວ່າງໄດ້ຖ້າບໍ່ມີວັນໝົດອາຍຸ', null=True, verbose_name='ວັນໝົດອາຍຸ'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product', verbose_name='ສິນຄ້າ'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, help_text='ເພີ່ມ batch ໃໝ່ — ລະບົບຈະອັບເດດຈຳນວນຂາຍລວມໃຫ້', verbose_name='ຈຳນວນໃນຊຸດນີ້'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຕົ້ນທຶນ/ຫນ່ວຍ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='ສິນຄ້າ'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.purchaseorder', verbose_name='ໃບສັ່ງຊື້'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='ຈຳນວນ'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ລວມແຖວ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.employee', verbose_name='ພະນັກງານສັ່ງຊື້'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີສັ່ງຊື້'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ລໍຖ້າ'), ('COMPLETED', 'ສຳເລັດ'), ('CANCELLED', 'ຍົກເລີກ')], default='PENDING', max_length=30, verbose_name='ສະຖານະ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='ຜູ້ສະໜອງ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຍອດລວມ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ອີເມວ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_address',
            field=models.TextField(verbose_name='ທີ່ຢູ່'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_name',
            field=models.CharField(max_length=100, verbose_name='ຊື່ຜູ້ສະໜອງ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_tel',
            field=models.CharField(max_length=20, verbose_name='ເບີໂທ'),
        ),
    ]
