# Generated by Django 4.2.27 on 2026-08-14 07:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_importdetail_options_alter_imports_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຕົ້ນທຶນ/ໜ່ວຍ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ຕົ້ນທຶນ/ໜ່ວຍ (ກີບ)'),
        ),
    ]
