# Generated by Django 4.2.27 on 2026-07-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ຊື່ (ລາວ)')),
                ('name_th', models.CharField(blank=True, max_length=100, verbose_name='ชื่อ (ไทย)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ຊື່ (ລາວ)')),
                ('name_th', models.CharField(blank=True, max_length=200, verbose_name='ชื่อ (ไทย)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (EN)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='ຄຳອະທິບາຍ (ລາວ)')),
                ('description_th', models.TextField(blank=True, verbose_name='คำอธิบาย (ไทย)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True, help_text='ລິ້ງຮູບຈາກ CDN (ແນະນຳສຳລັບ production — ບໍ່ຫາຍເມື່ອ deploy)')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
        ),
    ]
