# Generated by Django 4.2.27 on 2026-07-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'ໝວດໝູ່ (Category)', 'verbose_name_plural': 'ໝວດໝູ່ (Categories)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'ສິນຄ້າ (Product)', 'verbose_name_plural': 'ສິນຄ້າ (Products)'},
        ),
    ]
