# Generated by Django 4.2.27 on 2026-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='ຈຳນວນໃນສາງ (Stock)'),
        ),
    ]
