# Generated by Django 4.2.27 on 2026-07-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_missing_i18n_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'ໝວດໝູ່ສິນຄ້າ', 'verbose_name_plural': 'ໝວດໝູ່ສິນຄ້າ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'ສິນຄ້າ', 'verbose_name_plural': 'ສິນຄ້າ'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='ຊື່ຫຼັກທີ່ລູກຄ້າເຫັນເມື່ອເລືອກພາສາລາວ', max_length=100, unique=True, verbose_name='ຊື່ໝວດ (ລາວ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, help_text='ປ່ອຍວ່າງໄດ້ຖ້າບໍ່ໃຊ້ພາສາອັງກິດ', max_length=100, verbose_name='ຊື່ໝວດ (EN)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_th',
            field=models.CharField(blank=True, help_text='ປ່ອຍວ່າງໄດ້ຖ້າບໍ່ໃຊ້ພາສາໄທ', max_length=100, verbose_name='ຊື່ໝວດ (ไทย)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='ໃຊ້ໃນ URL ເຊັ່ນ /shop/?category=matcha — ປ່ອຍວ່າງລະບົບຈະສ້າງໃຫ້', max_length=120, unique=True, verbose_name='ລະຫັດ URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='ເລືອກໝວດທີ່ສິນຄ້ານີ້ຢູ່', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='ໝວດໝູ່'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ວັນທີສ້າງ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='ອະທິບາຍສັ້ນໆໃຫ້ລູກຄ້າອ່ານ', verbose_name='ລາຍລະອຽດ (ລາວ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='ລາຍລະອຽດ (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_th',
            field=models.TextField(blank=True, verbose_name='ລາຍລະອຽດ (ไทย)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='ອັບໂຫຼດຈາກເຄື່ອງ — ໃນ production ແນະນຳໃຊ້ລິ້ງ URL ຂ້າງລຸ່ມ', upload_to='products/', verbose_name='ຮູບສິນຄ້າ (ອັບໂຫຼດ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='ວາງລິ້ງຮູບຈາກ CDN/Supabase — ບໍ່ຫາຍເມື່ອ redeploy', verbose_name='ລິ້ງຮູບ (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='ປິດ = ລູກຄ້າບໍ່ເຫັນສິນຄ້ານີ້ໃນຮ້ານ', verbose_name='ເປີດຂາຍ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='ຕິກເພື່ອໃຫ້ສິນຄ້າຂຶ້ນໜ້າທຳອິດຂອງຮ້ານ', verbose_name='ແນະນຳໜ້າຫຼັກ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='ຊື່ທີ່ສະແດງໃນໜ້າຮ້ານ', max_length=200, verbose_name='ຊື່ສິນຄ້າ (ລາວ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='ຊື່ສິນຄ້າ (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_th',
            field=models.CharField(blank=True, max_length=200, verbose_name='ຊື່ສິນຄ້າ (ไทย)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ລາຄາຂາຍເປັນກີບລາວ — ຕົວຢ່າງ 120000', max_digits=12, verbose_name='ລາຄາ (ກີບ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='ປ່ອຍວ່າງໄດ້ — ລະບົບຈະສ້າງອັດຕະໂນມັດ', max_length=220, unique=True, verbose_name='ລະຫັດ URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, help_text="ຈຳນວນທີ່ຂາຍໄດ້ດຽວນີ້. ຖ້າ = 0 ລູກຄ້າຈະເຫັນ 'ໝົດ — ຈອງໄດ້'", verbose_name='ຈຳນວນຄົງເຫຼືອ'),
        ),
    ]
