# Generated by Django 4.2.27 on 2026-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productvariant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ຊື່ (ລາວ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='ຄຳອະທິບາຍ (ລາວ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ຊື່ (ລາວ)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='display_name',
            field=models.CharField(max_length=120, verbose_name='ຊື່ສະແດງ (ລາວ)'),
        ),
    ]
