# Generated by Django 4.2.27 on 2026-06-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='answer_lo',
            field=models.TextField(blank=True, verbose_name='ຄຳຕອບ (ລາວ)'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_lo',
            field=models.CharField(blank=True, max_length=255, verbose_name='ຄຳຖາມ (ລາວ)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Answer (EN)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_th',
            field=models.TextField(verbose_name='ຄຳຕອບ (ไทย)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (EN)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_th',
            field=models.CharField(max_length=255, verbose_name='ຄຳຖາມ (ไทย)'),
        ),
    ]
